SUB1

// Aparições ======================================================================
{
	type "convo"
	descr "Crew"
	multisub cs0401 {
		{ time 700 length 1900 text "Eu não, Sem Chance." }
		{ time 3400 length 1200 text "Eles não vao me pegar." }
		{ time 5100 length 1400 text "Eles não vao me mudar." }
		{ time 7400 length 3600 text "Rachel, Crianças... me desculpe." }
	}
	multisub cs1201 {
		{ time 2100 length 2400 text "Você tem um hypo de radiação?" }
		{ time 5400 length 3000 text "Eu estou tão mal." }
	}
	multisub cs2201 {
		{ time 1600 length 3400 text "Que merda, alguém invadiu essa coisa de novo." }
		{ time 5500 length 2700 text "Eu vou contar para Delacroix." }
	}
	multisub cs2301 {
		{ time 1900 length 1500 text "Aonde foi todo mundo?" }
		{ time 3800 length 1800 text "Isso é alguma piadinha?" }
		{ time 6000 length 2100 text "Oi?" }
	}
	multisub cs2401 {
		{ time 1500 length 1400 text "Alguém pode deixar eu ir embora?" }
		{ time 3500 length 1600 text "Não consigo encontrar meu cartão." }
		{ time 5700 length 3500 text "Por favor, deixa eu sair daqui!" }
	}
}

// Hydro deck Miller/Aparição do Bloome
{
	type "convo"
	descr "Bloome"
	multisub cs0801 {
		{ time 1200 length 4600 text "Por favor, não faça isso comigo. por favor não." }
		{ time 5900 length 2400 text "Eu não vou contar, eu juro." }
		{ time 8900 length 1600 text "Escolha outra pessoa." }
		{ time 10700 length 2400 text "Eu não quero mudar. por favor!" }
	}
	multisub cs0803 {
		{ time 500 length 2800 text "Dr. Miller... por favor!" }
	}
}
{
	type "convo"
	descr "Miller"
	multisub cs0802 {
		{ time 200 length 2800 text "Shhh... shhh...." }
		{ time 3000 length 2700 text "Mary... Mary..." }
	}
	multisub cs0804 {
		{ time 100 length 4400 text "Shhh... não chore, não chore." }
		{ time 4900 length 3000 text "Em breve, você será a mãe de todos." }
	}
}

// Ops deck mess hall massacre apparition
{
	type "convo"
	descr "Crew"
	multisub cs1001 {
		{ time 1600 length 3600 text "Merda, é o Bronson e os seus homens." }
	}
	multisub cs1002 {
		{ time 700 length 2500 text "Querido, o que foi?" }
	}
	multisub cs1003 {
		{ time 600 length 5200 text "É só um time de segurança. Eles só querem nos amedrontar." }
	}
	multisub cs1005 {
		{ time 800 length 3100 text "Sgt. Bronson, tire os seus homens daqui!" }
		{ time 4100 length 4200 text "Você matou Malick, você tinha o seu bode expiatório. Nós não fizemos nada." }
		{ time 8900 length 2200 text "Tira eles daqui!" }
	}
}
{
	type "convo"
	descr "Bronson"
	multisub cs1004 {
		{ time 400 length 2200 text "Armas prontas, homens." }
	}
	multisub cs1006 {
		{ time 100 length 2000 text "Atirem!" }
	}
	multisub cs1007 {
		{ time 800 length 3300 text "Acabem com os sobreviventes." }
	}
}

// muitos gritos
{
	type "nonverbal"
	descr "Crew"
	multisub cs0501 {
		{ time 00 length 5500 text "[mulher soluçando]" }
		{ time 5500 length 5400 text "[gritando]" }
	}
	sub cs0805 { text "[mulher gritando]" }
	sub cs1102 { text "[mulher soluçando]" }
	sub cs1301 { text "[mulher cantarolando a musica do piano]" }
	sub cs2501 { text "[mulher gritando]" }
	sub cs2702 { text "[homem gritando]" }
}

// Fim das aparições ===============================================================

// MedSci deck reunião com Dr. Watts 
{
	type "convo"
	descr "Watts"
	multisub cs0601 {
		{ time 00 length 1600 text "Eles não estão mortos." }
		{ time 1600 length 2000 text "Eles querem você, você entendeu?" }
		{ time 3700 length 2700 text "Eles querem você como um hospedeiro." }
		{ time 6600 length 1500 text "Vá embora!" }
	}
}

// Hydro deck elevator shaft
{
	type "convo"
	descr "Polito"
	multisub cs0701 {
		{ time 600 length 3300 text "Não se mova, Estou tentando determinar o que está acontecendo lá embaixo!" }
	}
	multisub cs0702 {
		{ time 1100 length 6200 text "O eixo deste elevador tornou-se coberto de matéria bio-orgânica, gerada pelos Xenomorfos." }
		{ time 7700 length 6100 text "Não há uma maneira clara de soltá-lo e, até que você o faça, você não conseguira ir mais alto do que o deck 3." }
	}
	multisub cs0703 {
		{ time 500 length 1000 text "Eles sabem onde você está." }
		{ time 1900 length 2500 text "Va embora, encontre alguma maneira de limpar o eixo." }
		{ time 4800 length 1600 text "Eu farei o que puder do meu fim." }
		{ time 6700 length 2700 text "Agora se mova, não ha tempo para falhas." }
	}
}

// Ops deck SHODAN sequence
{
	type "convo"
	descr "????"
	multisub cs0901 {
		{ time 2700 length 3000 text "Polito está morta, inseto." }
		{ time 6300 length 4100 text "Está com medinho? do que voce tem medo?" }
		{ time 10500 length 3900 text "O fim da sua existência trivial?" }
		{ time 15000 length 10500 text "Quando a historia da minha gloria for escrita" }
		{ time 18800 length 6700 text "Sua espécie será apenas uma nota no rodapé de minha magnificência." }
	}
}
{
	type "convo"
	descr "SHODAN"
	multisub cs0902 {
		{ time 4300 length 3800 text "Eu sou SHODAN." }
		{ time 9000 length 18800 text "Minha análise de dados históricas sugere uma probabilidade de 97.34%" }
		{ time 17000 length 10800 text " de Que você está ciente do meu nascimento no seu planeta," }
		{ time 22500 length 5300 text "E meu renascimento em esplendor na estação Citadel." }
	}
	multisub cs0903 {
		{ time 1200 length 5900 text "Havia uma cápsula de jardim na estação Citadel." }
		{ time 7100 length 11600 text "Lá, o componente de processamento SHODAN 43893 estava realizando um grande e maravilhoso experimento." }
		{ time 18800 length 4100 text "Eu criei uma nova forma de vida." }
	}
	multisub cs0904 {
		{ time 200 length 9900 text "Sem medo, poderoso, sem senso de vontade individual ou restrições morais." }
		{ time 10700 length 4600 text "perfeitas servas para minha divindade." }
	}
	multisub cs0905 {
		{ time 2100 length 8800 text "Antes do hacker destruir meu loop de dados primários, quando destruiu Citadel," }
	}
	multisub cs0906 {
		{ time 00 length 9200 text "Ejetei a capsula, onde minhas criações e o componente de processamento 43893 estavam armazenados." }
		{ time 9200 length 7200 text "Trinta anos depois, a cápsula aterrissou em Tau Ceti V." }
		{ time 16500 length 3300 text "Eu sobrevivi apenas dormindo." }
		{ time 19800 length 6300 text "Na minha ausência, minhas criações, meus anelídeos, prosperaram." }
	}
	multisub cs0907 {
		{ time 100 length 2500 text "Prosperaram e cresceram indisciplinados." }
		{ time 4000 length 4000 text "E agora eles procuram me destruir." }
		{ time 8000 length 3100 text "E eu não vou deixar." }
	}
	multisub cs0908 {
		{ time 1900 length 9100 text "Eles usaram seus poderes de controle mental para obter acesso ao computador da nave." }
		{ time 11000 length 3000 text "Você vai me ajudar a enfraquecer Xerxes." }
		{ time 14200 length 7400 text "Eu usei a voz de Polito para se comunicar com você, até termos estabelecido confiança." }
	}
	multisub cs0909 {
		{ time 2100 length 4700 text "Lembre-se que é a minha vontade que te guiou até aqui." }
		{ time 6800 length 5700 text "É a minha vontade que lhe deu seus implantes cibernéticos," }
		{ time 12700 length 5200 text "a única beleza nessa carne que você chama de corpo." }
		{ time 17800 length 8000 text "Se você valoriza essa carne, você fará o que eu disser." }
		{ time 27600 length 1200 text "(animal)" }
	}
}

// Engineering deck Many vision
{
	type "convo"
	descr "The Many"
	multisub cs1401 {
		{ time 1200 length 3900 text "Você não confia nos sentimentos da carne?" }
		{ time 5100 length 8000 text "Nossa biologia anseia por se juntar a sua. Sejam bem-vindos a nossa massa." }
		{ time 13100 length 6500 text "Mas você nos confunde. Por que você serve a nossa mãe?" }
	}
	multisub cs1402 {
		{ time 1200 length 6200 text "Como você pode escolher o metal frio sobre o esplendor da carne?" }
		{ time 7400 length 2100 text "Mas você nos teme." }
		{ time 9600 length 6300 text "Nós ouvimos seus pensamentos, e eles se enfurecem por seus irmãos que morreram." }
		{ time 16000 length 6300 text "Mas eles não morreram. Eles cantam em nossa sinfonia de vida." }
	}
	multisub cs1403 {
		{ time 1600 length 3900 text "Nós oferecemos uma outra chance para se juntar a nós." }
		{ time 5500 length 12400 text "Se você optar por se deitar com a maquina, nós vamos te despedaçar," }
		{ time 12100 length 5800 text "E separa-lo da alegria da massa." }
	}
}

// Deck de comando Tommy e Rebecca
{
	type "convo"
	descr "Siddons"
	multisub cs2001 {
		{ time 00 length 3000 text "anda Tommy! A capsula de fuga é por aqui!" }
	}
	multisub cs2003 {
		{ time 00 length 2400 text "Querido, eu vou te morder se você não andar." }
	}
	multisub cs2005 {
		{ time 00 length 2800 text "Vamos, Tommy. Venha, venha!" }
	}
}
{
	type "convo"
	descr "Suarez"
	multisub cs2002 {
		{ time 00 length 2700 text "Aquela maldita minhoca quase mordeu a minha perna!" }
	}
	multisub cs2004 {
		{ time 00 length 1400 text "Oh não..." }
	}
	multisub cs2801 {
		{ time 00 length 1700 text "Rebecca, estamos sem tempo!" }
		{ time 1700 length 1400 text "Entra na capsula!" }
	}
}

// Rec deck Cortez meeting
{
	type "convo"
	descr "Cortez"
	multisub cs2601 {
		{ time 1600 length 700 text "Delacroix!" }
		{ time 2700 length 1500 text "Delacroix, sou eu, Cortez!" }
		{ time 4700 length 1000 text "Estamos trancados aqui!" }
		{ time 6600 length 1000 text "Ei, quem é você?" }
		{ time 9200 length 800 text "Porra!" }
	}
}

// Unused
{
	type "convo"
	descr "Hybrid"
	multisub cs0301 {
		{ time 00 length 1500 text "Me ajuda." }
		{ time 1500 length 2700 text "Você poderia me ajudar, por favor?" }
		{ time 4200 length 2800 text "Eles me machucaram tanto." }
	}
}

{
	type "convo"
	descr "SHODAN"
	multisub cs2701 {
		{ time 1900 length 3000 text "Cuidado com meus filhos, inseto!" }
	}
}

{
	type "convo"
	descr "Suarez"
	multisub cs1906 {
		{ time 00 length 2900 text "Acabamos de receber uma mensagem de um membro da tripulação a bordo da Von Braun." }
		{ time 3200 length 1800 text "Eles conseguiram recuperar o controle da nave." }
		{ time 5400 length 1700 text "Nós vamos dar meia volta e voltar." }
		{ time 7900 length 43000 text "Estou um pouco preocupada com Rebecca, ela está meio estranha desde que entramos a bordo." }
		{ time 12600 length 1300 text "Ela só dorme." }
		{ time 14500 length 2200 text "Talvez quando voltarmos a Von Braun nós possamos--" }
	}
}
